language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
before_script:
  - cd expoTest
  - npm install -g npm@latest
script:
  - npm ci
  - npx expo login --non-interactive -u 
  - npx expo publish --non-interactive
