language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
before_script:
  - cd expoTest
  - npm install -g npm@latest
  - npm install -g expo-cli@latest
script:
  - npm ci
  - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
  - npx expo publish --non-interactive
